### ISSUE TITLE
release-members step now fails on all collection objects

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/item-release#69]
This is the error message: release-members : Failed to retrieve resource: put https://sul-lyberservices-prod.stanford.edu/workflow/dor/objects/druid:xs573nh8717/workflows/releaseWF/release-members?current-status=queued (HTTP status 500)

**Comment by blalbrit** [comment]
From the wfservice app logs:

2016-10-25 16:53:21,192 ERROR [edu.stanford.sulair.dlss.dor.resource.WorkflowResource] - edu.stanford.sulair.dlss.dor.DorRuntimeExeption: Error during conditional workflow update
Current Workflow dor:releaseWF:release-members for object druid:zn653qj0117
Has status: waiting.
Was expecting: queued
	at edu.stanford.sulair.dlss.dor.service.WorkflowServiceImpl$1.doInTransactionWithoutResult(WorkflowServiceImpl.java:66)
	at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:33)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:128)
--
	at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:698)
	at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:891)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
	at java.lang.Thread.run(Thread.java:662)

 2016-10-25 16:53:21,241 DEBUG [edu.stanford.sulair.dlss.dor.service.WorkflowService] - sendObjectUpdateMessage for druid=druid:zn653qj0117
 2016-10-25 16:53:23,329 DEBUG [edu.stanford.sulair.dlss.dor.resource.WorkflowQueueResource] - Starting WorkflowQueueResource.getWorkflowQueue()
 2016-10-25 16:53:23,329 DEBUG [edu.stanford.sulair.dlss.dor.resource.WorkflowQueueResource] -   Waiting- dor:versioningWF:start-accession
 2016-10-25 16:53:23,329 DEBUG [edu.stanford.sulair.dlss.dor.resource.WorkflowQueueResource] -   Completed- dor:versioningWF:review-version
 2016-10-25 16:53:23,329 DEBUG [edu.stanford.sulair.dlss.dor.resource.WorkflowQueueResource] - laneId: default
 2016-10-25 16:53:23,890 DEBUG [edu.stanford.sulair.dlss.dor.resource.WorkflowQueueResource] - Starting WorkflowQueueResource.getWorkflowQueue()
